### ISSUE TITLE
Unable to load layout editor

### ISSUE THREAD

**Issue by michal-hradis** [DCGM/pero_ocr_web#2]
147.229.13.150 - - [17/Sep/2019 21:23:46] "GET /layout_analysis/get_image_result/052cd675-93b5-46aa-a10e-1ec0636afd96/49436775-aadf-42d6-946b-592985b7524c HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 2309, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 2295, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 1741, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 1816, in full_dispatch_request
    return self.finalize_request(rv)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 1831, in finalize_request
    response = self.make_response(rv)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 1982, in make_response
    reraise(TypeError, new_error, sys.exc_info()[2])
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/_compat.py", line 34, in reraise
    raise value.with_traceback(tb)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/flask/app.py", line 1974, in make_response
    rv = self.response_class.force_type(rv, request.environ)
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/werkzeug/wrappers.py", line 921, in force_type
    response = BaseResponse(*_run_wsgi_app(response, environ))
  File "/home/ihradis/env/tf/lib/python3.6/site-packages/werkzeug/test.py", line 923, in run_wsgi_app
    app_rv = app(environ, start_response)
TypeError: 'dict' object is not callable
The view function did not return a valid response. The return type must be a string, tuple, Response instance, or WSGI callable, but it was a dict.

**Comment by michal-hradis** [comment]
added jsonify
